export const HERO_ROLES = {
  'Abaddon': ['Offlane', 'Support', 'Hard Support'],
  'Alchemist': ['Safe Lane', 'Mid Lane'],
  'Ancient Apparition': ['Support', 'Hard Support'],
  'Anti-Mage': ['Safe Lane'],
  'Arc Warden': ['Safe Lane', 'Mid Lane'],
  'Axe': ['Offlane'],
  'Bane': ['Support', 'Hard Support'],
  'Batrider': ['Mid Lane', 'Offlane', 'Support'],
  'Beastmaster': ['Offlane'],
  'Bloodseeker': ['Safe Lane', 'Mid Lane'],
  'Bounty Hunter': ['Offlane', 'Support'],
  'Brewmaster': ['Offlane'],
  'Bristleback': ['Safe Lane', 'Offlane'],
  'Broodmother': ['Mid Lane', 'Offlane'],
  'Centaur Warrunner': ['Offlane'],
  'Chaos Knight': ['Safe Lane', 'Offlane'],
  'Chen': ['Support', 'Hard Support'],
  'Clinkz': ['Safe Lane', 'Mid Lane'],
  'Clockwerk': ['Offlane', 'Support', 'Hard Support'],
  'Crystal Maiden': ['Support', 'Hard Support'],
  'Dark Seer': ['Offlane'],
  'Dark Willow': ['Support', 'Hard Support'],
  'Dawnbreaker': ['Offlane', 'Support'],
  'Dazzle': ['Support', 'Hard Support'],
  'Death Prophet': ['Mid Lane', 'Offlane'],
  'Disruptor': ['Support', 'Hard Support'],
  'Doom': ['Offlane'],
  'Dragon Knight': ['Mid Lane', 'Offlane'],
  'Drow Ranger': ['Safe Lane'],
  'Earth Spirit': ['Support', 'Mid Lane'],
  'Earthshaker': ['Offlane', 'Support'],
  'Elder Titan': ['Offlane', 'Support'],
  'Ember Spirit': ['Safe Lane', 'Mid Lane'],
  'Enchantress': ['Support', 'Hard Support', 'Offlane'],
  'Enigma': ['Offlane', 'Support'],
  'Faceless Void': ['Safe Lane'],
  'Grimstroke': ['Support', 'Hard Support'],
  'Gyrocopter': ['Safe Lane'],
  'Hoodwink': ['Support', 'Hard Support', 'Mid Lane'],
  'Huskar': ['Mid Lane', 'Safe Lane'],
  'Invoker': ['Mid Lane'],
  'Io': ['Support', 'Hard Support'],
  'Jakiro': ['Support', 'Hard Support'],
  'Juggernaut': ['Safe Lane'],
  'Keeper of the Light': ['Support', 'Hard Support'],
  'Kunkka': ['Mid Lane', 'Offlane'],
  'Legion Commander': ['Offlane'],
  'Leshrac': ['Mid Lane', 'Safe Lane'],
  'Lich': ['Support', 'Hard Support'],
  'Lifestealer': ['Safe Lane'],
  'Lina': ['Mid Lane', 'Safe Lane', 'Support'],
  'Lion': ['Support', 'Hard Support'],
  'Lone Druid': ['Safe Lane', 'Mid Lane', 'Offlane'],
  'Luna': ['Safe Lane'],
  'Lycan': ['Safe Lane', 'Offlane'],
  'Magnus': ['Offlane', 'Mid Lane'],
  'Marci': ['Safe Lane', 'Offlane', 'Support'],
  'Mars': ['Offlane'],
  'Medusa': ['Safe Lane', 'Mid Lane'],
  'Meepo': ['Mid Lane', 'Safe Lane'],
  'Mirana': ['Support', 'Mid Lane', 'Safe Lane'],
  'Monkey King': ['Safe Lane', 'Mid Lane'],
  'Morphling': ['Safe Lane', 'Mid Lane'],
  'Muerta': ['Safe Lane', 'Support'],
  'Naga Siren': ['Safe Lane'],
  "Nature's Prophet": ['Offlane', 'Safe Lane', 'Support'],
  'Necrophos': ['Mid Lane', 'Offlane', 'Safe Lane'],
  'Night Stalker': ['Offlane'],
  'Nyx Assassin': ['Support', 'Offlane'],
  'Ogre Magi': ['Support', 'Hard Support'],
  'Omniknight': ['Offlane', 'Support'],
  'Oracle': ['Support', 'Hard Support'],
  'Outworld Destroyer': ['Mid Lane'],
  'Pangolier': ['Mid Lane', 'Offlane'],
  'Phantom Assassin': ['Safe Lane'],
  'Phantom Lancer': ['Safe Lane'],
  'Phoenix': ['Offlane', 'Support', 'Hard Support'],
  'Primal Beast': ['Mid Lane', 'Offlane'],
  'Puck': ['Mid Lane', 'Offlane'],
  'Pudge': ['Mid Lane', 'Offlane', 'Support', 'Safe Lane'],
  'Pugna': ['Mid Lane', 'Support'],
  'Queen of Pain': ['Mid Lane'],
  'Razor': ['Safe Lane', 'Mid Lane', 'Offlane'],
  'Riki': ['Safe Lane'],
  'Rubick': ['Support', 'Hard Support'],
  'Sand King': ['Offlane'],
  'Shadow Demon': ['Support', 'Hard Support'],
  'Shadow Fiend': ['Mid Lane', 'Safe Lane'],
  'Shadow Shaman': ['Support', 'Hard Support'],
  'Silencer': ['Support', 'Hard Support', 'Mid Lane'],
  'Skywrath Mage': ['Support', 'Hard Support', 'Mid Lane'],
  'Slardar': ['Offlane'],
  'Slark': ['Safe Lane'],
  'Snapfire': ['Support', 'Hard Support', 'Mid Lane'],
  'Sniper': ['Mid Lane', 'Safe Lane'],
  'Spectre': ['Safe Lane'],
  'Spirit Breaker': ['Offlane', 'Support'],
  'Storm Spirit': ['Mid Lane'],
  'Sven': ['Safe Lane'],
  'Techies': ['Support', 'Hard Support'],
  'Templar Assassin': ['Mid Lane', 'Safe Lane'],
  'Terrorblade': ['Safe Lane'],
  'Tidehunter': ['Offlane'],
  'Timbersaw': ['Offlane', 'Mid Lane'],
  'Tinker': ['Mid Lane'],
  'Tiny': ['Mid Lane', 'Safe Lane', 'Support'],
  'Treant Protector': ['Support', 'Hard Support'],
  'Troll Warlord': ['Safe Lane'],
  'Tusk': ['Support', 'Offlane'],
  'Underlord': ['Offlane'],
  'Undying': ['Support', 'Hard Support'],
  'Ursa': ['Safe Lane'],
  'Vengeful Spirit': ['Support', 'Hard Support'],
  'Venomancer': ['Support', 'Hard Support'],
  'Viper': ['Mid Lane', 'Offlane'],
  'Visage': ['Offlane', 'Mid Lane', 'Support'],
  'Void Spirit': ['Mid Lane'],
  'Warlock': ['Support', 'Hard Support'],
  'Weaver': ['Safe Lane', 'Offlane'],
  'Windranger': ['Mid Lane', 'Offlane', 'Support'],
  'Winter Wyvern': ['Support', 'Hard Support'],
  'Witch Doctor': ['Support', 'Hard Support'],
  'Wraith King': ['Safe Lane', 'Offlane'],
  'Zeus': ['Mid Lane', 'Support'],
  'Ringmaster': ['Support', 'Hard Support'],
  'Kez': ['Safe Lane', 'Mid Lane']
};

export const heroHasRole = (heroName, roleFilter, openDotaRoles) => {
  if (roleFilter === 'All') return true;
  
  if (HERO_ROLES[heroName]) {
    return HERO_ROLES[heroName].includes(roleFilter);
  }

  // Fallback
  switch (roleFilter) {
    case 'Safe Lane': return openDotaRoles.includes('Carry');
    case 'Mid Lane': return openDotaRoles.includes('Nuker') || openDotaRoles.includes('Escape') || openDotaRoles.includes('Carry');
    case 'Offlane': return openDotaRoles.includes('Initiator') || openDotaRoles.includes('Durable');
    case 'Support': return openDotaRoles.includes('Support');
    case 'Hard Support': return openDotaRoles.includes('Support') || openDotaRoles.includes('Disabler');
    default: return true;
  }
};
